import {
  AlertTriangle,
  ArrowRight,
  Bot,
  BrainCircuit,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock,
  Command,
  Copy,
  Cpu,
  Database,
  FileText,
  FolderKanban,
  GitFork,
  Globe,
  Layers,
  LayoutDashboard,
  LineChart,
  Loader2,
  Lock,
  MessageSquare,
  Network,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Sliders,
  Sparkles,
  Terminal,
  Trash2,
  Upload,
  User,
  Zap,
  X
} from "lucide-react";

export const ICON_REGISTRY = {
  ai: { Bot, BrainCircuit, Cpu, Sparkles, Zap },
  knowledge: { Database, FileText, Upload, Search },
  graph: { Network, GitFork, Layers },
  memory: { Clock, Layers, FolderKanban },
  settings: { Settings, Sliders, Lock },
  security: { Shield, ShieldCheck, Lock },
  analytics: { LineChart, LayoutDashboard },
  ui: { ArrowRight, Check, CheckCircle2, ChevronDown, ChevronRight, Command, Copy, Loader2, Plus, RefreshCw, Terminal, Trash2, User, X, AlertTriangle, Globe }
};
